### ISSUE TITLE
Rename the project!

### ISSUE THREAD

**Issue by Williangalvani** [ArduPilot/UAVLogViewer#101]
We are not constrained to .tlog files, so we shouldn't have a name that implies so

**Comment by Williangalvani** [comment]
keywords:  Ardupilot, flight, analysis, review

**Comment by davidbuzz** [comment]
more keywords: logger, 3D, share, plotting, drone, graph, visualiser

**Comment by davidbuzz** [comment]
ArduVis3D ?
