### ISSUE TITLE
export ODTs files or CSVs 

### ISSUE THREAD

**Issue by patrickelectric** [ArduPilot/UAVLogViewer#111]
It would be nice to export ODT files where each message is a tab
or multiple CSV files that are ziped for each message.

**Comment by kd0aij** [comment]
@patrickelectric In case you didn't know, pymavlink has some tools for dumping and extracting portions of log files.

**Comment by Williangalvani** [comment]
done in https://github.com/ArduPilot/UAVLogViewer/pull/341
