### ISSUE TITLE
Fix selected values initial height

### ISSUE THREAD

**Issue by patrickelectric** [ArduPilot/UAVLogViewer#138]
After selecting some values, the messages in the search box starts to move down, make it harder to select others messages.
The selected messages layout should have an initial fixed height or be in a different place to not resize while selecting messages. 
![image](https://user-images.githubusercontent.com/1215497/76989401-05c93400-6925-11ea-8e20-66b82ea37694.png)

**Comment by Williangalvani** [comment]
I'm thinking of limiting it's height so it gets a scrollbar after some size, hopefully @biakp can help with that!
