### ISSUE TITLE
Make messages visible at least up to cursor..

### ISSUE THREAD

**Issue by Hwurzburg** [ArduPilot/UAVLogViewer#185]
preferably always show all messages in the list...syncing to the timeline cursor is okay, but unfortunately, the messages stop in time well before the cursor...should at least be a few in the scroll list beyond the cursor time stamp...

**Comment by Williangalvani** [comment]
what about some visual feedback? make the ones up to the cursor bold, maybe?

**Comment by Hwurzburg** [comment]
that sounds fine, but the big issue, is that you cant see messages all the way up to the cursor point...they stop before that

**Comment by Williangalvani** [comment]
Right! I missed your point. Can you share a log where that happens?

**Comment by Hwurzburg** [comment]
I will try  to find the one I was having problems with....

**Comment by Hwurzburg** [comment]
cant find the logs this was doing it...so will close until I see it again...
