### ISSUE TITLE
Wrong time shown in Cesium player

### ISSUE THREAD

**Issue by Hwurzburg** [ArduPilot/UAVLogViewer#187]
https://www.dropbox.com/s/p4ut300nu3mu2ok/2020-06-14%2015-55-06.bin?dl=0

log was taken on June14....player shows Jul 6 2020

**Comment by Williangalvani** [comment]
any chance it was actually June 15?

**Comment by Hwurzburg** [comment]
![Capture](https://user-images.githubusercontent.com/6076534/84691409-b685a600-af09-11ea-95a7-00965b52acd0.PNG)

**Comment by Williangalvani** [comment]
I mean the date you flew it. do you happen to remember the aproximate time as well?

**Comment by Williangalvani** [comment]
does this look right?

**Comment by Hwurzburg** [comment]
Its in the log...yesterday .....6/14/2020 3:53PM local time

**Comment by Williangalvani** [comment]
Right, my bad! I need to check how cesium time works

**Comment by Williangalvani** [comment]
Best I can do for now!
![Screenshot from 2020-06-15 23-45-56](https://user-images.githubusercontent.com/4013804/84726095-74d51980-af62-11ea-81a0-ee57b02938e6.png)

Unfortunately adding localization to Cesium is going to take some time... I'll have to:
 - guess timezone from gps (found a lib for that)
 - override some internals of cesium to render the localizated string

**Comment by Hwurzburg** [comment]
UTC is fine...just having stuff in the future was a bit odd before!
