### ISSUE TITLE
Presets cannot be deleted

### ISSUE THREAD

**Issue by Williangalvani** [ArduPilot/UAVLogViewer#191]

**Comment by Williangalvani** [comment]
fixed by https://github.com/ArduPilot/UAVLogViewer/commit/bfb65d146f57d308a923a8d6b89f9a8e8590547b

**Comment by Hwurzburg** [comment]
can you move the trashcan further away from the name...easy to click and delete rather than select....especially if the preset name is only a few letters...should right justified in the display box
