### ISSUE TITLE
Handle log records with instance numbers

### ISSUE THREAD

**Issue by kd0aij** [ArduPilot/UAVLogViewer#205]
Example log file with instance numbers:
https://drive.google.com/file/d/1YPALgny9zl6ro1g2XTmw6YUXm4IVJ_1K/view?usp=sharing

sample plot generated by MAVExplorer:
![image](https://user-images.githubusercontent.com/2300221/87719687-fcd05e00-c770-11ea-8c83-722fe2403fdb.png)

**Comment by Williangalvani** [comment]
Hi, do you have one where multiple instances are populates? I need to check how to handle the individual instances

**Comment by kd0aij** [comment]
https://drive.google.com/file/d/1iclPeUAob_OuHYJnZJUyAJICAnpOxmAi/view?usp=sharing

![image](https://user-images.githubusercontent.com/2300221/88246394-97d8a480-cc57-11ea-8998-2d288976c496.png)
