### ISSUE TITLE
Servos 1-4 and 1-8 presets incorrect

### ISSUE THREAD

**Issue by kd0aij** [ArduPilot/UAVLogViewer#206]
channels are specified as RCOU.Ch1-4 but the correct names are RCOU.C1, RCOU.C2, etc.

Also on Win10/Chrome 83.0.4103.116 "Save Preset" doesn't appear to do anything at all after entering the name for the new preset.

**Comment by Williangalvani** [comment]
Hi @kd0aij , can you check if this works properly in plotbeta.ardupilot.org?

**Comment by kd0aij** [comment]
yes, looks good, and save preset is working too
