### ISSUE TITLE
Subtraction doesn't work

### ISSUE THREAD

**Issue by durka** [ArduPilot/UAVLogViewer#262]
This error message is a little gaslight-y: 
![image](https://user-images.githubusercontent.com/47007/110994705-2ca72400-8347-11eb-8eaf-28a219a45290.png)

Workaround is to use addition instead of subtraction:
![image](https://user-images.githubusercontent.com/47007/110994741-40528a80-8347-11eb-92cc-937114710d03.png)

**Comment by durka** [comment]
Sometimes you don't get an error message, but the expression involving subtraction just doesn't show up on the plot.

**Comment by durka** [comment]
Would you mind reopening this, or should I open a new issue? https://github.com/ArduPilot/UAVLogViewer/pull/306#issuecomment-1082519873

**Comment by Williangalvani** [comment]
let's reopen it

**Comment by Williangalvani** [comment]
it seems to work if you try plotting `ATT.DesPitch - ATT.Pitch` (with spaces). The regex probably needs some tweaks

**Comment by Williangalvani** [comment]
Can you verify that this new fix works? It should be live in http://plotbeta.ardupilot.org after this [action](https://github.com/ArduPilot/UAVLogViewer/runs/5748500629?check_suite_focus=true) finishes. You should probably do ctrl+f5 to ignore the browser cache
