### ISSUE TITLE
YAW Orientation display

### ISSUE THREAD

**Issue by NuvemUAV** [ArduPilot/UAVLogViewer#265]
Hi guys,

We use our FC mounted -90 degrees on Z axis.

It seems the LOG viwer doesn't check this parameter to plot the drone on the map:

<img width="590" alt="Screen Shot 2021-03-26 at 09 16 16" src="https://user-images.githubusercontent.com/32582069/112630441-59ae0900-8e14-11eb-8334-c0b05ec3e7a1.png">

**Comment by Williangalvani** [comment]
Hi, that is because there's only one 3d model for quads and the FRAME_TYPE param is not bein taken into account. I'll try to get to this soon.

**Comment by Williangalvani** [comment]
@NuvemUAV would you mind testing https://plotbeta.ardupilot.org/ ?

**Comment by NuvemUAV** [comment]
Works perfectly @Williangalvani 

Thanks!

<img width="1341" alt="Screen Shot 2021-04-09 at 13 40 03" src="https://user-images.githubusercontent.com/32582069/114213333-379aa780-9939-11eb-8e83-26411405c50d.png">
