### ISSUE TITLE
tkoff / landing altitude not tied to ground

### ISSUE THREAD

**Issue by teodoryantcheff** [ArduPilot/UAVLogViewer#266]
![image](https://user-images.githubusercontent.com/4791195/112824734-90de1d80-9093-11eb-8167-478bd7761662.png)

Trajectory from an arduplane .bin dataflash log. There's a constant offset for the entire flight.
[Here's a link](https://drive.google.com/drive/folders/1FLJNY_BEkBr61HaWhL3NJ2kpd6Dfq9cj?usp=sharing) to the .bin file.

Is there a way to "clamp"  to gound or offset altitude reading?

**Comment by teodoryantcheff** [comment]
Changing the trajectory source does not help it one bit.

**Comment by teodoryantcheff** [comment]
Just to illustrate the point more clearly:

![Peek 2021-03-29 14-05](https://user-images.githubusercontent.com/4791195/112828087-eb797880-9097-11eb-8817-67cdd6653241.gif)

**Comment by Williangalvani** [comment]
@teodoryantcheff can you try http://plotbeta.ardupilot.org now?

**Comment by Williangalvani** [comment]
by "now" I mean after https://github.com/ArduPilot/UAVLogViewer/actions/runs/706607274 finishes

**Comment by teodoryantcheff** [comment]
@Williangalvani Perfect! Thanks!
