### ISSUE TITLE
hangs on ESC fields

### ISSUE THREAD

**Issue by mattdholmes00** [ArduPilot/UAVLogViewer#289]
Viewer is hanging when trying to access any ESC fields.  [Log file example.](https://www.dropbox.com/s/ds5qxecbu73f9te/20210718_00000031.BIN?dl=0)

**Comment by Williangalvani** [comment]
Hi, thank you for reporting this!

There are two issues here. the first one is that we actually freeze instead of returning an error. The second one is that we assume the instance numbers start at zero, while in this log they are from 5 to 8 (or something like this)

**Comment by Williangalvani** [comment]
The changes are up at http://plotbeta.ardupilot.org
![image](https://user-images.githubusercontent.com/4013804/126737824-227d977e-2989-48eb-b402-afcf4fb3c8b8.png)
![image](https://user-images.githubusercontent.com/4013804/126737837-1d850b23-d513-432c-95f9-26497053f4bd.png)

**Comment by mattdholmes00** [comment]
thanks, this is resolved for me
