### ISSUE TITLE
Graph display never ends

### ISSUE THREAD

**Issue by msfujino** [ArduPilot/UAVLogViewer#319]
I use Mission Planner to download a .bin file from flash ROM and analyze it with UAVLogViewer. 
However, sometimes, the graph display never ends. 
Is there a problem with the .bin file? 
Is there a way to find out?

![NeverEnd](https://user-images.githubusercontent.com/50060737/142794085-ed395d9b-9d9c-4cd2-9361-dff74cad6489.jpg)

**Comment by Williangalvani** [comment]
there should be an error in the browser console with more information

**Comment by msfujino** [comment]
I have tried "Google Chrome" and "Microsoft Edge" as browsers, but the graph display never ends. 
Attach the bin(ZIP) file. I would be happy if you could confirm it.

[1 1970-01-01 9-00-01.zip](https://github.com/ArduPilot/UAVLogViewer/files/7740137/1.1970-01-01.9-00-01.zip)

**Comment by Williangalvani** [comment]
It turned out that your log is missing the MODE message, and the code was breaking while trying to load mode change information. it should work fine now in http://plotbeta.ardupilot.org
