### ISSUE TITLE
Constant expression breaks preset saving

### ISSUE THREAD

**Issue by durka** [ArduPilot/UAVLogViewer#346]
I tried to save a preset of the following setup: 
![image](https://user-images.githubusercontent.com/47007/184014379-aaea689d-19e0-4ec2-9da0-a03179997048.png)

However, only CTUN.ThI, and PIDY.I actually made it into the saved preset. It seems like the save routine gives up at the constant expression.

**Comment by Williangalvani** [comment]
Hi, can you check if the issue is fixed in https://plotbeta.ardupilot.org/ ?

**Comment by durka** [comment]
Yes it seems to be fixed on beta now!
