### ISSUE TITLE
Unable to view AOA.AOA

### ISSUE THREAD

**Issue by stw2nf** [ArduPilot/UAVLogViewer#407]
![Type Error AoA](https://github.com/ArduPilot/UAVLogViewer/assets/57158922/cc9ebb17-1bc5-4b37-b9d6-dab8491be4e3)
The message is present and can be viewed through Mission Planner

**Comment by VedantBhosle31** [comment]
Can you send that log file? 
So that we can recreate the error.

**Comment by stw2nf** [comment]
Absolutely:
https://drive.google.com/file/d/1GtShN0oJSSshZmo3HvvmEhW9Hhi8usBr/view?usp=drive_link

It is there, I can pull from ardupilog and Mission Planner, for some reason not UAV Log Viewer though. I have tried Chrome and Edge as browsers.

**Comment by axelisart** [comment]
Hi, just to say that this problem still occurs.

**Comment by Lazersfly** [comment]
This is still a problem in both the production and beta log viewer websites. 

Happy to donate to the project if an option. This tool makes my post-flight analysis so much easier than the alternatives out there, would love to support the work to fix existing bugs and make the project better in general!

**Comment by Williangalvani** [comment]
Hi, that should be fixed on master, can you give it a try?

**Comment by Lazersfly** [comment]
AOA.AOA is working on plotbeta.ardupilot.org! Thank you!
