### ISSUE TITLE
Interface hangs on log file with only ATT data

### ISSUE THREAD

**Issue by qqqlab** [ArduPilot/UAVLogViewer#418]
I tried to graph a small log file with only ATT data. This works fine if I use the "Plots Setup" section and add for example ATT.Roll.

The interface hangs if I select a "Presets" or a "Plot Individual Field".

I suspect the problem is that the application expects GPS data in the log file.

Sample file with 3 records types: FMT(FMT), FMT(ATT), ATT: [output.zip](https://github.com/user-attachments/files/17361719/output.zip)

**Comment by Williangalvani** [comment]
Thanks for reporting. the fix should be live at http://plotbeta.ardupilot.org in about 10min

fixed by bcf88c81807c828e7bd1c3d858a5f068a0e1556d
